# Generated by Django 3.1.1 on 2020-09-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200909_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
