# Generated by Django 3.1.1 on 2020-09-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_group_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
