# Generated by Django 3.1.1 on 2020-09-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_group_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
